name = "webdav-player-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
WEBDAV_URL = "https://webdav.cloud.mail.ru/"
WEBDAV_USERNAME = "nowfow@mail.ru"
WEBDAV_PASSWORD = "FpeY7pxjVeQJEJpEjaar"

[[d1_databases]]
binding = "DB"
database_name = "webdav_player"
database_id = "your-database-id" 